# Fortran CircleCI configuration file

# jobs:
#   build: # name of your job
#     machine: # executor type
#       image: ubuntu-2004:202010-01
#     resource_class: medium
#     steps:
#         pre:
#             - sudo apt-get update
#             - sudo apt-get install neofetch
#             - bash ci/test.sh

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Testing"
          command: |
            ./ci/test.sh
