# Fortran CircleCI configuration file

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
        pre:
            - sudo apt-get update
            - sudo apt-get install neofetch

            - bash ci/test.sh
